name: Verify/lint/test Python code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
        key: pip-${{ hashFiles('requirements.txt') }}
        path: |
          ~/.cache/python
          ~/.python
          ~/.pip
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install black pytest pylint
        pip install -r requirements.txt

  format:
    needs: pip
    runs-on: ubuntu-latest
    steps:
    - run: find -name '*.py' -exec black --check {} +

  lint:
    needs: pip
    runs-on: ubuntu-latest
    steps:
    - run: find -name '*.py' -exec pylint {} +

  test:
    needs: pip
    runs-on: ubuntu-latest
    steps:
    - run: python -m unittest tests/*.py

  podman:
    runs-on: ubuntu-latest
    steps:
      - name: Bulid container
        run: podman build . -t the-lone-dancer
      - name: Test in container
        run: podman run the-lone-dancer python3.8 -m unittest tests/*.py
