name: Verify/lint/test Python code

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install black pytest pylint
        pip install -r requirements.txt
    - name: Format with black
      run: |
        find -name '*.py' -exec black --check {} +
    - name: Lint with pylint
      run: |
        find -name '*.py' -exec pylint {} +
    - name: Run unittests
      run: |
        python -m unittest
